"""hosts.local.json loader. Default path: --hosts-file, else $LCM_RELIABILITY_HOSTS, else the host-prep lane's file.

Format (see hosts.example.json): ``{"hosts": {"<name>": {"python", "src", "sha", "hermes_version"}}}``.
A host whose python, src or hermes_home is under the real ``~/.hermes`` (lexically or resolved) is refused:
that is a live install, never a harness host. ``verify`` proves the configured sha: git HEAD for a git tree, or
a tree-hash manifest (``<src>/../tree-manifest.json``) written at host-prep time from ``git archive <sha>``.

    python hosts.py --write-manifest <src dir> --sha <sha> --git-repo <repo holding the sha>   # host prep
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import pwd
import re
import subprocess
import tarfile
import tempfile
from pathlib import Path

DEFAULT = "/Users/m1/Codex/lcmx-reliability/hosts/hosts.local.json"


def real_hermes_dir() -> Path:
    return Path(pwd.getpwuid(os.getuid()).pw_dir).resolve() / ".hermes"


def under_real_hermes(path, hermes_dir: Path | None = None) -> bool:
    live = (hermes_dir or real_hermes_dir()).resolve()
    lexical = Path(os.path.normpath(Path(path).expanduser().absolute()))
    live_lexical = Path(os.path.normpath((hermes_dir or Path(pwd.getpwuid(os.getuid()).pw_dir) / ".hermes").absolute()))
    return any(p == root or root in p.parents
               for p in (lexical, Path(path).expanduser().resolve()) for root in (live, live_lexical))


SKIP_DIRS = {"__pycache__", ".git", "node_modules"}


def tree_hash(root: Path) -> tuple[str, int]:
    """sha256 over sorted (relative path, content sha256) of every file; generated byte-code and install
    metadata (``__pycache__``, ``*.pyc``, ``*.egg-info``) are excluded. Every symlink, to a file OR a directory,
    is an entry with its target string (a directory symlink is not descended)."""
    entries = []
    for dirpath, dirs, files in os.walk(root):
        for name in [d for d in dirs if (Path(dirpath) / d).is_symlink()]:
            entries.append(f"{(Path(dirpath) / name).relative_to(root).as_posix()}\0link:{os.readlink(Path(dirpath) / name)}\n")
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.endswith(".egg-info") and not (Path(dirpath) / d).is_symlink()]
        for name in files:
            if name.endswith(".pyc"):
                continue
            path = Path(dirpath) / name
            rel = path.relative_to(root).as_posix()
            entries.append(f"{rel}\0link:{os.readlink(path)}\n" if path.is_symlink()
                           else f"{rel}\0{hashlib.sha256(path.read_bytes()).hexdigest()}\n")
    return hashlib.sha256("".join(sorted(entries)).encode()).hexdigest(), len(entries)


def manifest_path(src) -> Path:
    return Path(src).parent / "tree-manifest.json"


def write_manifest(src: Path, sha: str, git_repo: Path) -> dict:
    """Host prep: prove the on-disk tree equals ``git archive <sha>`` and record its tree hash."""
    blob = subprocess.run(["git", "-C", str(git_repo), "archive", "--format=tar", sha], capture_output=True, check=True).stdout
    with tempfile.TemporaryDirectory() as tmp, tarfile.open(fileobj=io.BytesIO(blob)) as tar:
        tar.extractall(tmp, filter="data")
        archived = tree_hash(Path(tmp))
    on_disk = tree_hash(src)
    if archived != on_disk:
        raise ValueError(f"{src} does not match git archive {sha}: {on_disk} != {archived}")
    record = {"sha": sha, "tree_sha256": on_disk[0], "files": on_disk[1], "verified_against": f"git archive {sha} in {git_repo}"}
    manifest_path(src).write_text(json.dumps(record, indent=1) + "\n")
    return record


def verify(name: str, host: dict) -> dict:
    """Prove the tree at ``src`` IS the configured sha; raise otherwise."""
    src, sha = Path(host["src"]), host["sha"]
    if (src / ".git").exists():
        def git(*args):  # every git command must succeed, or the tree is not verified
            done = subprocess.run(["git", "-C", str(src), *args], capture_output=True, text=True)
            if done.returncode:
                raise ValueError(f"host {name}: git {' '.join(args)} failed: {done.stderr.strip()[:200]}")
            return done.stdout.strip()
        head = git("rev-parse", "HEAD")
        dirty = git("status", "--porcelain", "--untracked-files=all")  # untracked files can shadow modules
        ignored_py = git("ls-files", "--others", "--ignored", "--exclude-standard", "--", "*.py")
        if head != sha or dirty or ignored_py:
            raise ValueError(f"host {name}: git HEAD {head} != {sha}, or the tree has modified/untracked files "
                             f"or ignored *.py: {(dirty or ignored_py)[:200]}")
        return {"method": "git HEAD", "head": head}
    mpath = manifest_path(src)
    if not mpath.exists():
        raise ValueError(f"host {name}: {src} is not a git tree and has no {mpath}")
    manifest = json.loads(mpath.read_text())
    actual = tree_hash(src)[0]
    if manifest.get("sha") != sha or manifest.get("tree_sha256") != actual:
        raise ValueError(f"host {name}: tree hash {actual} or manifest sha {manifest.get('sha')} does not match {sha}")
    return {"method": "tree-manifest", "tree_sha256": actual, "manifest": str(mpath)}


def hosts_file(arg: str | None) -> Path:
    return Path(arg or os.environ.get("LCM_RELIABILITY_HOSTS") or DEFAULT)


def load(path: Path, names: list[str] | None = None, hermes_dir: Path | None = None) -> dict:
    hosts = json.loads(Path(path).read_text())["hosts"]
    if names:
        unknown = [n for n in names if n not in hosts]
        if unknown:
            raise ValueError(f"unknown hosts {unknown}; {path} lists {sorted(hosts)}")
        hosts = {n: hosts[n] for n in names}
    for name, host in hosts.items():
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", name) or name in (".", ".."):
            raise ValueError(f"host name {name!r} is not a single safe path component")
        for key in ("python", "src", "sha"):
            if not host.get(key):
                raise ValueError(f"host {name}: missing {key!r}")
        for key in ("python", "src", "hermes_home"):
            if host.get(key) and under_real_hermes(host[key], hermes_dir):
                raise ValueError(f"host {name}: {key} {host[key]} is under the live ~/.hermes; refused")
        if not Path(host["src"]).is_dir():
            raise ValueError(f"host {name}: src {host['src']} is not a directory")
    return hosts


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--write-manifest", type=Path, required=True)
    ap.add_argument("--sha", required=True)
    ap.add_argument("--git-repo", type=Path, required=True)
    a = ap.parse_args()
    print(json.dumps(write_manifest(a.write_manifest, a.sha, a.git_repo)))
